# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTIIcWhOpjTYIr9Lye9UHC61ebCARsKk
"""

# Cannon ball: 1 Kg, 8 cm Radius; 100 m/s v0; 30º angle, p = 1.22 kg/m^3; C = 0.47

import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

def cannon(r,t): # Gravity considered 9.8 m/s^2
  m = 1
  R = 0.08
  p = 1.22
  C = 0.47
  g = 9.8
  x = r[0]
  dx = r[1]
  z = r[2]
  dz = r[3]
  dxdt = dx
  dzdt = dz
  CC = (np.pi*R**2*p*C)/(2*m) # Just for ease of writing
  ddxdt = -CC*dxdt*np.sqrt(dxdt**2+dzdt**2)
  ddzdt = -g-CC*dzdt*np.sqrt(dxdt**2+dzdt**2)
  return np.array([dxdt,ddxdt,dzdt,ddzdt],float)


v0 = 100
TH = np.radians(30)
r0 = (0,v0*np.cos(TH),0,v0*np.sin(TH))

#def timefinal(fint):
#  time = np.linspace(0,fint,200)
#  rsolv = sp.integrate.odeint(cannon,r0,time)
#  return(rsolv[-1,3])

#impact = sp.optimize.fsolve(timefinal,10)


tfinals = np.linspace(2.6,8,2000) # As fsolve didn't worked before, now I'm just checking for a match.
impact = 0
iteration = 1
impactpos = 0

for n in tfinals:
  impa = sp.integrate.odeint(cannon,r0,np.linspace(0,n,100))
  iteration += 1
  if abs(impa[-1,2])<0.01:
    impact = n
    impactpos = iteration

rsol = sp.integrate.odeint(cannon,r0,np.linspace(0,impact,200))

fig=plt.figure(figsize=(8,6))

ax0=plt.subplot2grid((1,1),(0,0))
ax0.plot(rsol[:,0],rsol[:,2]) # Part 1
ax0.axhline(color="black")
ax0.set_ylabel("z [m]")
ax0.set_xlabel("x [m]")
ax0.set_title("Cannonball trayectory")

#ax1=plt.subplot2grid((2,1),(1,0)) # This was for checking the times, if you want to, remember to put the (2,1) in the 2grid above
#ax1.plot(np.linspace(0,impact,len(rsol[:,2])),rsol[:,2]) # Part 1
#ax1.plot(np.arange(0,len(finalss)),finalss)
#ax1.axhline()
#ax1.set_ylabel("z [m]")
#ax1.set_xlabel("t [s]")
#ax1.set_title("Cannonball")

plt.tight_layout()
plt.show()

# Part 2 and 3:

print("""
La bala de cañon cae en """,round(impact,2),""" segundos
y recorre una distancia de """,round(rsol[-1,0],2),""" metros
""")
# rsol[-1,0] is the last position in x, and as we solve until point of impact, that is the distance if we start from 0